### ISSUE TITLE
GPU の tensor を変換しようとしてエラーが出る。

### ISSUE THREAD

**Issue by syu-tan** [ry-takashima/python_asr#1]
@ry-takashima 
素晴らしい書籍とコードをありがとうございます。大変お勉強になりました。

`04dnn_hmm/02_train_dnn.py` のファイル実行時です。

環境は 
```
OS: ubuntu 18.04
python 3.7.3
GPU : 3090
torch : 1.8.1+cu111
```
torch は 3090 を動かすために少し高いですがエラーとは別問題かと思います。

ちなみに GCP の GPU k80 + torch 1.6.* でも同様のエラーは確認できます。

GPU 上で実行すると以下のエラーが出ます。
```
Traceback (most recent call last):
  File "02_train_dnn.py", line 502, in <module>
    label=phase+' error')
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3021, in plot
    **({"data": data} if data is not None else {}), **kwargs)
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 493, in _plot_args
    x, y = index_of(xy[-1])
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1687, in index_of
    y = _check_1d(y)
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1339, in _check_1d
    return np.atleast_1d(x)
  File "<__array_function__ internals>", line 6, in atleast_1d
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/numpy/core/shape_base.py", line 65, in atleast_1d
    ary = asanyarray(ary)
  File "/home/syu/anaconda3/envs/asr/lib/python3.7/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
どうぞよろしくお願いします。

**Comment by syu-tan** [comment]
エラーの原因としては GPU 上の tensor を CPU 上に移行せずに plot しようとしたことが原因です。

修正のプルリクを送ろうとしたのですが、許可が出ていなかったので以下の対応または、それ以外の場所の CPU 移行の対応をよろしくお願いします。

`04dnn_hmm/02_train_dnn.py` のファイルにて、`line 385` の部分
```
-             error_history[phase].append(epoch_error)
+            error_history[phase].append(epoch_error.cpu())
```

**Comment by ry-takashima** [comment]
@syu-tan 
ご指摘頂き誠にありがとうございます。またご丁寧に解決法までご教示頂きまして、大変助かりました。
何故か私の環境ではエラーが出なかったのですが、ご教示頂いたコードが正しい実装ですので、以下のファイルをその通りに修正いたしました。
`04dnn_hmm/02_train_dnn.py`
`04dnn_hmm/04_train_dnn_fbank.py`
今後ともどうぞよろしくお願いいたします。

**Comment by syu-tan** [comment]
@ry-takashima 
お早いご対応大変感謝します。ありがとうございます。
こちらこそ今後ともよろしくお願いします。
